import { StyleSheet } from "react-native";

const style = StyleSheet.create({
    container: {
        flexDirection: "row",
        minHeight: 100,
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderColor: "#e1e5e9",
        borderWidth: 1,
        justifyContent: "space-between",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
        width: "100%",
    },
    markedTask: {
        width: "100%",
        flexDirection: "row",
        minHeight: 100,
        backgroundColor: "#f8f9fa",
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderColor: "#dee2e6",
        borderWidth: 1,
        justifyContent: "space-between",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    text: {
        color: "#2c3e50",
        fontSize: 18,
        fontWeight: "600",
        marginBottom: 4,
        lineHeight: 24,
    },
    description: {
        color: "#6c757d",
        fontSize: 14,
        lineHeight: 20,
        maxWidth: 200,
    },
    textContainer: {
        flex: 1,
        justifyContent: "center",
        paddingRight: 12,
    },
    actionsContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    doneButton: {
        backgroundColor: "#28a745",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 0,
        shadowColor: "#28a745",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    doneButtonText: {
        color: "white",
        fontSize: 14,
        fontWeight: "600",
        textAlign: "center",
    },
    deleteButton: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: "#fff5f5",
        borderWidth: 1,
        borderColor: "#fed7d7",
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#28a745",
        marginRight: 12,
    },
    statusIndicatorDone: {
        backgroundColor: "#6c757d",
    },
    priorityBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: "#fff3cd",
        borderWidth: 1,
        borderColor: "#ffeaa7",
    },
    priorityText: {
        fontSize: 10,
        fontWeight: "600",
        color: "#856404",
    },
    dateText: {
        fontSize: 12,
        color: "#adb5bd",
        marginTop: 4,
        fontStyle: "italic",
    }
});

export default style;